name: deploy-to-dj-rex
on: 
  push:
    branches:
      # Push events on main branch
      - main
    paths-ignore:
    - 'doc/**'
    - README.md
jobs:
  sftp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SFTP Deploy
      # You may pin to the exact commit or the version.
      # uses: wlixcc/SFTP-Deploy-Action@cf8d9e5b504ce4aab358e6231495c72a7dc18dcd
      uses: wlixcc/SFTP-Deploy-Action@1.1
      with:
        # username
        username: 'github'
        # your sftp server
        server: 'dj-rex.de'
        # your sftp server port, default to 22
        port: 22 # default is 22
        # you can copy private_key from your *.pem file, keep format
        ssh_private_key: ${{secrets.DJREXPRIVATE}}
        # will put all file under this path
        local_path: './src/*' # default is ./*
        # files will copy to under remote_path
        remote_path: 'html/cueGenerator' # default is /
        # sftp args
        #args: # optional
