name: deploy-to-dj-rex
on: 
  push:
    branches:
      # Push events on main branch
      - main
    paths-ignore:
    - 'doc/**'
jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to my ❤️
      uses: up9cloud/action-rsync@v1.1
      env:
        HOST: dj-rex.de
        KEY: ${{secrets.DJREXPRIVATE}}
        TARGET: /var/www/html/

        VERBOSE: true
        USER: ubuntu
        ARGS: -az --exclude=/.git/ --exclude=/.github/ --exclude=/doc/
        #SSH_ARGS: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
        #SOURCE: ./public/

        PRE_SCRIPT: |
          echo start at:
          date -u
        POST_SCRIPT: "echo done at: && date -u"
