name: learn-github-actions
on: 
  push:
    branches:
      # Push events on main branch
      - main
    paths-ignore:
    - 'doc/**'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: rsync deployments
        # You may pin to the exact commit or the version.
        # uses: contention/rsync-deployments@980b08d70e94c4ac0169ee5c5acc9ace2fe8ccd4
        env:
          GITHUB_WORKSPACE: .
        args: ["-avzr --delete", "--exclude .git --exclude .github --exclude /doc/", "github@dj-rex.de:/var/www/html/"]
        secrets: ["DEPLOY_KEY"]
        uses: contention/rsync-deployments@v1.0.0
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v

